# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot = { 
      initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
      initrd.kernelModules = [ ];#"amdgpu" ];
      kernelModules = [ "kvm-amd" ];
      #kernelParams = [
      #  "video=eDP-1:1980x1080@165"
      #  "video=HDMI-A-1:1980x1080@60"
      #];
      extraModulePackages = with config.boot.kernelPackages; [ rtw89 ];
    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d1360a49-5445-43f5-88e5-54780efdafca";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F996-11F6";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e61fff74-673b-4e1d-99c4-1f8b8079fa49"; }
    ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
